src/pages/MainPage.jsx
feature/#1-홈화면레이아웃 -> develop
홈화면에서 카드 드래그 시 onClick이 적용되는 오류 발견하여
기본 드래그 작동방지 함수 제거
=> [FEAT] 홈화면 드래그 동작방지 함수 제거

src/components/common/Header.jsx, src/index.css
Fix/#10-폰트적용문제해결 -> develop
폰트 적용 문제 해결
=> Fix: 폰트적용 문제 해결 (#10)

src/pages/LevelInfoPage.jsx
refactor/#12-숙련도상세페이지코드정리 -> develop
반복되는 테이블 -> 더미 데이터 사용, map 함수로 변경해서 간단하게 정리
=> Refactor: 숙련도 상세 페이지 코드 정리

src/pages/LevelInfoPage.jsx, src/pages/LevelPage.jsx
feature/#19-숙련도페이지디자인수정 -> develop
배경 도형 css 수정
https://github.com/user-attachments/assets/862a31c5-accb-48b4-867d-0e79487f968d
=> Style: 숙련도 페이지 배경 디자인 수정

src/pages/LevelInfoPage.jsx, src/pages/LevelPage.jsx
feature/#25-숙련도페이지기능추가-> develop
숙련도 페이지에서 버튼 클릭 시 해당 숙련도에 따라 상세 페이지의 내용이 달라지는 기능 추가
https://github.com/user-attachments/assets/889beccb-5ec9-401e-96d3-27c5bfc17f0d
=> Feat: 숙련도 페이지 기능 추가

src/pages/BoardMorePage.jsx, src/pages/BoardWritePage.jsx
style/#27-글쓰기페이지디자인수정 -> develop
정렬 아이콘 애니메이션, 카테고리 박스 길이 수정
https://github.com/user-attachments/assets/ca6a72fd-f6f5-464e-b61d-90a08ac34170
=> Style: 글쓰기 페이지 디자인 수정

src/pages/BoardMorePage.jsx, src/pages/BoardWritePage.jsx
feature/#29-게시판페이지기능추가 -> develop
게시판 더보기 페이지 페이지네이션 구현
https://github.com/user-attachments/assets/32652568-0e8f-4152-a951-0ff367f847e3
=> Feature/#29 게시판페이지기능추가

package-lock.json, package.json, src/assets/icons/common/cancelIcon.svg, src/assets/icons/common/menuIcon.svg, src/components/common/Header.jsx, src/components/location/CafeArea.jsx, src/components/location/InitialArea.jsx, src/components/location/LocationContent.jsx, src/components/location/StationArea.jsx, src/components/location/ThemeArea.jsx, src/hooks/useDevice.js, src/pages/LocationPage.jsx, src/pages/LoginPage.jsx
style/#23-헤더및로그인페이지반응형 -> develop
헤더, 로그인 페이지 배경 페이지 반응형 구현
=> Style: 헤더, 로그인 페이지 반응형 구현

.vite/deps/_metadata.json, .vite/deps/package.json, package-lock.json, package.json, src/App.jsx, src/apis/API.jsx, src/apis/theme/getProficiencyListAPI.js, src/components/map/MyMap.jsx, src/components/map/NaverMapContainer.jsx, src/pages/LevelInfoPage.jsx, src/pages/LevelPage.jsx, src/pages/MapPage.jsx, src/utils/API.jsx, vite.config.js
feature/#32-api연결세 -> develop
- API 연결 세팅
- 숙련도 목록조회 API 연결
=> Feat: API 연결 세팅 및 숙련도 목록조회 API 연결

netlify.toml
fix/#34-netlify에러해결 -> develop
netlify 404 에러 해결
=> Fix: netlify 에러 해결

package-lock.json, src/apis/theme/getGenresListAPI.js, src/pages/GenrePage.jsx
feature/#38-장르페이지api임시연결 -> develop
장르 목록 api에서 데이터 받아옴
=> Feature: 장르 페이지 API 임시 연결

package-lock.json, package.json, src/app/App.jsx, src/features/auth/api/authAPI.js, src/features/auth/model/authSchema.js, src/features/auth/ui/SignupModal.jsx, src/pages/LoginPage.jsx, src/pages/SignupPage.jsx, src/pages/UserInfoPage.jsx, src/shared/components/Header.jsx
feature/#55-회원가입및로그인기능구현 -> develop
- 회원가입 기능 구현
- 로그인 기능 구현
=> Feature: 회원가입 및 로그인 기능 구현

package-lock.json, package.json, src/app/API.jsx, src/features/auth/api/authAPI.js, src/pages/LoginPage.jsx, src/shared/components/ContentCard.jsx, src/shared/components/Header.jsx, src/shared/components/HeaderProfileModal.jsx, src/shared/utils/dataUtils.js, src/shared/utils/formatUtils.js, vite.config.js
fix/#74-목록조회에러수정및기타수정 -> develop
- 목록 조회 에러 해결
- 콘텐츠 카드 기능 추가
- 로그인 에러 해결
=> Feat: 목록 조회 에러 수정 및 기타 수정

src/app/App.jsx, src/features/auth/api/authAPI.js, src/features/auth/ui/AuthCallback.jsx, src/features/auth/ui/AuthError.jsx, src/pages/LoginPage.jsx, src/pages/SignupPage.jsx
feature/#76-소셜로그인구현 -> develop
- 카카오 소셜 로그인 구현
- 구글 소셜 로그인 구현
=> Feat: 소셜 로그인 구현

src/features/auth/ui/AgreeSection.jsx, src/features/auth/ui/CompleteSection.jsx, src/features/auth/ui/NicknameSection.jsx, src/pages/LoginPage.jsx, src/pages/SignupPage.jsx
style/#82-회원가입페이지스타일수정 -> develop
- 회원가입 페이지 스타일 수정
- 회원가입 페이지 모바일 반응형 구현
=> Style: 회원가입 페이지 스타일 수정

src/features/level/api/levelAPI.js, src/features/main/ui/GenreSection.jsx, src/features/main/ui/LevelSection.jsx, src/shared/components/ContentCard.jsx
feature/#86-홈화면추가기능구현 -> develop
=> Feature/#86 홈화면추가기능구현

src/features/auth/api/authAPI.js, src/features/auth/ui/CompleteSection.jsx, src/features/survey/api/surveyAPI.js, src/features/survey/model/surveyAtom.jsx, src/features/survey/model/surveyGenreList.js, src/features/survey/model/surveyPreferenceList.js, src/features/survey/ui/SurveyGenreSection.jsx, src/features/survey/ui/SurveyHeadcountSection.jsx, src/features/survey/ui/SurveyInfoSection.jsx, src/features/survey/ui/SurveyPositionSection.jsx, src/features/survey/ui/SurveyPreferenceSection.jsx, src/features/survey/ui/SurveyProficiencySection.jsx
feature/#90-성향조사페이지api연결 -> develop
성향 조사 페이지 api 연결
=> Feat: 성향조사 API 연결

src/features/genre/ui/GenreTabSection.jsx
style/#95-장르페이지디자인수정 -> develop
장르 탭 디자인 오류 수정
=> [Style] 장르 페이지 탭 디자인 수정 (#95)

src/features/genre/api/genreAPI.js, src/features/genre/ui/GenreContentSection.jsx, src/shared/components/BottomSheet.jsx, src/shared/components/filter/OptionList.js, src/shared/components/filter/PeopleFilter.jsx, src/shared/components/filter/SortFilter.jsx
feature/#97-필터기능추가및수정 -> develop
모바일 필터 텍스트 활성화 기능 추가
리셋 버튼 적용 오류 해결
정렬 기준 필터링 기능 추가
인원수 필터 - 인원수 별로 다른 가격 표시 기능 추가
장르 api 호출 로직 수정
=> [FEAT] 필터 기능 추가 및 오류 수정 (#97)

src/features/level/api/levelAPI.js, src/features/level/model/levelData.js, src/features/level/ui/LevelContentSection.jsx, src/features/level/ui/LevelTabSection.jsx, src/features/levelInfo/ui/RangeItem.jsx, src/pages/LevelSearchPage.jsx
feature/#100-숙련도페이지레이아웃구현 -> develop
숙련도 페이지 레이아웃 구현
=> [FEAT] 숙련도 페이지 레이아웃 구현 (#100)

src/shared/components/filter/FilterStyles.js, src/shared/components/filter/PeopleFilter.jsx, src/shared/components/filter/RegionFilter.jsx, src/shared/components/filter/SortFilter.jsx
feature/#102-드롭다운효과구현 -> develop
필터 드롭다운 애니메이션 효과 구현
.
=> [FEAT] 필터 드롭다운 효과 구현 (#102)

src/features/level/ui/LevelTabSection.jsx, src/features/review/modal/reviewDataList.js, src/features/review/ui/EscapeResultDetails.jsx, src/features/review/ui/FlexibleRangeSelector.jsx, src/features/review/ui/RangeItem.jsx, src/features/review/ui/ReviewDropdown.jsx, src/features/review/ui/ReviewFirst.jsx, src/features/review/ui/ReviewLast.jsx, src/features/review/ui/ReviewSecond.jsx, src/features/review/ui/ReviewThird.jsx, src/features/review/ui/VisitDatePicker.jsx, src/shared/components/InfoBox.jsx, src/shared/components/ReviewStyle.js
bugfix/#119-후기작성모달UI수정 -> develop
일부 기능 수정
일부 디자인 수정
=> Fix: 후기 작성 모달 UI 수정 (#119)

package-lock.json, package.json, src/app/App.jsx, src/features/themeDetail/api/themeDetailAPI.js, src/features/themeDetail/ui/PriceTable.jsx, src/features/themeDetail/ui/ThemeInfoSection.jsx, src/features/themeDetail/ui/ThemeOverviewCard.jsx, src/features/themeDetail/ui/ThemeReview.jsx, src/features/themeDetail/ui/ThemeReviewSection.jsx, src/pages/ThemeDetailPage.jsx, src/shared/utils/dataUtils.js
feature/#125-테마상세페이지api연결 -> develop
- 테마 상세 조회 api 연결
- 테마 가격 조회 api 연결
- 테마 후기 조회 api 연결
=> Feat: 테마 상세 페이지 api 연결

src/features/review/api/postReviewAPI.js, src/features/review/ui/EscapeResultDetails.jsx, src/features/review/ui/FlexibleRangeSelector.jsx, src/features/review/ui/HintCounter.jsx, src/features/review/ui/InputBox.jsx, src/features/review/ui/RangeItem.jsx, src/features/review/ui/ReviewFirst.jsx, src/features/review/ui/ReviewLast.jsx, src/features/review/ui/ReviewSecond.jsx, src/features/review/ui/ReviewThird.jsx, src/features/review/ui/StarRating.jsx, src/features/review/ui/VisitDatePicker.jsx, src/features/themeDetail/model/reviewAtom.jsx, src/features/themeDetail/ui/ReviewWriteModal.jsx, src/shared/components/ReviewStyle.js
feature/#123-후기작성API연결 -> develop
후기 작성 API 연결
=> Feat: 후기 작성 API 연결 (#123)

src/features/like/api/themeLikeAPI.js, src/features/like/modal/likeAtom.jsx, src/features/mypage/api/favoriteThemesAPI.js, src/features/mypage/ui/favorites/ContentCardSection.jsx, src/features/mypage/ui/favorites/HeaderSection.jsx, src/features/mypage/ui/favorites/SortDropDown.jsx, src/pages/myPage/FavoritesPage.jsx, src/shared/components/ContentCard.jsx
feature/#137-찜한방탈출목록페이지구현-> develop
마이페이지 - 내가 찜한 방탈출 목록 구현
=> Feat: 마이페이지 찜한 방탈출 목록 페이지 구현, API 연결 (#137)

src/features/mypage/ui/preferences/GenreSection.jsx, src/features/mypage/ui/preferences/HeadcountSection.jsx, src/features/mypage/ui/preferences/InfoSection.jsx, src/features/mypage/ui/preferences/PositionSection.jsx, src/features/mypage/ui/preferences/PreferenceSection.jsx, src/features/mypage/ui/preferences/ProficiencySection.jsx, src/features/mypage/ui/preferences/SurveyTag.jsx, src/pages/NotFoundPage.jsx, src/pages/myPage/MyPage.jsx, src/pages/myPage/PreferencesPage.jsx
feature/#156-마이페이지일부반응형구현 -> develop
- 마이페이지 홈화면 모바일 반응형 구현
- 마이페이지 성향조사 페이지 모바일 반응형 구현
- 404 페이지 모바일 반응형 구현
=> Feat: 마이 페이지 일부 반응형 구현

src/features/mypage/model/favoriteAtom.js, src/features/mypage/ui/favorites/ContentCardSection.jsx, src/features/mypage/ui/favorites/FavoriteDropDown.jsx, src/pages/myPage/FavoritesPage.jsx, src/shared/styles/FilterStyles.js
feature/#160-내가찜한방탈출기능추가 -> develop
마이페이지 내가 찜한 방탈출 부분 인원수 정렬 기능 추가
=> Feat: 내가 찜한 방탈출 마이페이지 인원수 정렬 기능 추가 (#160)

src/features/like/modal/likeAtom.jsx, src/features/location/ui/LocationContentCard.jsx, src/features/mypage/ui/favorites/ContentCardSection.jsx, src/features/themeDetail/ui/ThemeOverviewCard.jsx, src/shared/components/ContentCard.jsx
feature/#166-좋아요기능구현 -> develop
- 기존 좋아요 기능 오류 해결
- 지역 페이지 좋아요 기능 구현
- 테마/후기 상세 페이지 좋아요 기능 구현
- 좋아요한 테마 목록 페이지 코드 리팩토링
=> Feat: 좋아요 기능 구현

src/features/mypage/ui/reservations/ReservationDropDown.jsx, src/features/mypage/ui/reservations/ReservedCard.jsx, src/features/review/ui/ReviewWriteModal.jsx, src/features/themeDetail/model/reviewAtom.jsx, src/pages/myPage/ReservationsPage.jsx
feature/#168-예약한방탈출관리기능수정 -> develop
예약힌 방탈출 카드에서 모달 열기 기능 추가
예약힌 방탈출 카드 드롭다운 기능 수정
=> Feat: 예약한 방탈출 관리 마이페이지 기능 수정 및 추가 (#168)

src/app/App.jsx, src/features/review/ui/EscapeResultDetails.jsx, src/features/review/ui/ReviewFirst.jsx, src/features/review/ui/ReviewSecond.jsx, src/features/review/ui/ReviewThird.jsx, src/features/review/ui/ReviewWriteModal.jsx, src/features/review/ui/VisitDatePicker.jsx, src/features/themeDetail/model/reviewAtom.jsx, src/shared/styles/DatePickerGlobalStyle.jsx
feature/#170-후기작성모달날짜선택기능수정 -> develop
후기 작성 모달 날짜 선택 부분 디자인, 기능 수정 및 추가
=> Feat: 후기 작성 모달 날짜 선택 부분 디자인, 기능 추가 및 수정 (#170)

src/features/review/ui/EscapeTimePicker.jsx
feature/#175-후기작성모달ui수정 -> develop
후기 작성 모달 탈출 시 시간 입력 기능 수정
=> Fix: 후기 작성 모달 탈출 성공 시 남은 시간 입력 기능 수정 (#175)

build_spec.yaml
chore/build_spec 수정 -> develop
build_spec.yml 파일 수정
=> Chore: build_spec.yaml 파일 outputArtifacts 수정
